### ISSUE TITLE
Hardware Fragen

### ISSUE THREAD

**Issue by MMonu** [robotfreak/FlipDot#2]
Sind bei deinen Annax-Flipboards die rechten Kontakte alle miteinander verbunden? Ich sehe nämlich viele Flipdot-Controller, welche sowohl das Reset und Set für jeden Pixel einzeln machen und dafür sowohl die "obere" als auch die "untere" Zeilenansteuerung individuell adressierbar haben. Oder hab ich die Funktionsweise einfach vollkommen missverstanden?

**Comment by robotfreak** [comment]
Beim Annax Flipdot kann man keine einzelnen Pixel ansteuern, immer nur ein komplettes Panel. Auf jedem Panel sitzt ein Spaltentreiber Modul. Das MainController Modul schiebt parallel auf allen 16 Zeilen die Pixel an/aus Informationen raus.
Siehe https://github.com/robotfreak/FlipDot/blob/master/Images/FlipDot-Ctrl1.jpg
